name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - azure-functions
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - azure-functions

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    env:
      NODE_VERSION: '18'
      PYTHON_VERSION: '3.10'
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: 'azure-functions-backend/requirements.txt'

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci
      
      - name: Install Backend Dependencies
        run: |
          cd azure-functions-backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          AZURE_API_KEY: ${{ secrets.AZURE_API_KEY }}
          AZURE_ENDPOINT: ${{ secrets.AZURE_ENDPOINT }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          VITE_API_URL: 'https://stock-analysis-backend.azurewebsites.net/api'
          VITE_DEV_MODE: 'false'
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: "/frontend"
          api_location: "/azure-functions-backend"
          output_location: "dist"
          app_build_command: "npm run build:azure"
          api_build_command: "pip install -r requirements.txt"
          action: "upload"
          
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
          app_location: "/frontend" 