name: Deploy Frontend to Azure Web App

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/webapp-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        cd frontend
        rm -rf node_modules package-lock.json
        npm install --legacy-peer-deps
        
    - name: Setup environment
      run: |
        cd frontend
        cp .env.production .env
        
    - name: Build
      run: |
        cd frontend
        npm run build
        
    - name: Copy startup script to dist
      run: |
        chmod +x frontend/startup.sh
        cp frontend/startup.sh frontend/dist/
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: stock-screen-web
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: frontend/dist 